#include "nato.h"
#include "wordmap.h"

const int nato_len = 65;

const struct wordmap nato_map[65] = {
  { ' ', "[space]"},
  { '\n', "[newline]"},
  { '.', "[dot]"},
  { '0', "ZERO" },
  { '1', "ONE" },
  { '2', "TWO" },
  { '3', "THREE" },
  { '4', "FOUR" },
  { '5', "FIVE" },
  { '6', "SIX" },
  { '7', "SEVEN" },
  { '8', "EIGHT" },
  { '9', "NINER" },
  { 'A', "ALFA" },
  { 'B', "BRAVO" },
  { 'C', "CHARLIE" },
  { 'D', "DELTA" },
  { 'E', "ECHO" },
  { 'F', "FOXTROT" },
  { 'G', "GOLF" },
  { 'H', "HOTEL" },
  { 'I', "INDIA" },
  { 'J', "JULIETT" },
  { 'K', "KILO" },
  { 'L', "LIMA" },
  { 'M', "MIKE" },
  { 'N', "NOVEMBER" },
  { 'O', "OSCAR" },
  { 'P', "PAPA" },
  { 'Q', "QUEBEC" },
  { 'R', "ROMEO" },
  { 'S', "SIERRA" },
  { 'T', "TANGO" },
  { 'U', "UNIFORM" },
  { 'V', "VICTOR" },
  { 'W', "WHISKEY" },
  { 'X', "X-RAY" },
  { 'Y', "YANKEE" },
  { 'Z', "ZULU" },
  { 'a', "alfa" },
  { 'b', "bravo" },
  { 'c', "charlie" },
  { 'd', "delta" },
  { 'e', "echo" },
  { 'f', "foxtrot" },
  { 'g', "golf" },
  { 'h', "hotel" },
  { 'i', "india" },
  { 'j', "juliett" },
  { 'k', "kilo" },
  { 'l', "lima" },
  { 'm', "mike" },
  { 'n', "november" },
  { 'o', "oscar" },
  { 'p', "papa" },
  { 'q', "quebec" },
  { 'r', "romeo" },
  { 's', "sierra" },
  { 't', "tango" },
  { 'u', "uniform" },
  { 'v', "victor" },
  { 'w', "whiskey" },
  { 'x', "x-ray" },
  { 'y', "yankee" },
  { 'z', "zulu" }
};

const struct wordmap *nato_alphabet = nato_map;
